INSERT INTO AFFILIATION (name) VALUES ('Babel');
INSERT INTO AFFILIATION (name) VALUES ('Iberia');
INSERT INTO AFFILIATION (name) VALUES ('Rhodes Island');
INSERT INTO AFFILIATION (name) VALUES ('Karlan Trade');